### ISSUE TITLE
Charging Status Icon

### ISSUE THREAD

**Issue by Veldkornet** [benct/lovelace-battery-entity-row#4]
I noticed that items which are charging do not show the charging icon as it does with the standard icon.
Could this be added?

Additionally, to add the battery state as secondary info (charging / not charging). Although I’d say the icon has priority.

**Comment by benct** [comment]
Support for charging indication added in `v1.1.0`. I do not have any battery entities with charging capabilities, so let me know if something is not working as expected.

**Comment by Veldkornet** [comment]
Nope, still not showing for me anyway. 

If you need an example to test on, you can install the HA app for iOS/Android and then just plug your phone into the charger.

**Comment by benct** [comment]
I tested it with other entities that have on/off states, and it works as I expected and in the same way as the default battery entities in HA. Make sure you clear cache/hard refresh/reload resources in HA.

Also, you need to enable charging indication. See readme.

**Comment by Veldkornet** [comment]
Aha, I didn't see the updated docs. I just assumed that it would just work 😁

Looks like things may be more complex than needed...

Is it expecting a true / false response specifically?

I can get it working with my Android as it has a binary sensor for charging. 

For my vacuum and the iOS devices, seems a bit more involved though...

The iOS devices seem to have a battery_state sensor which has charging / not charging. And the battery_level sensor has an attribute called battery_state, which then seems to reference the battery state sensor. 
Referencing this sensor as I did for the Android doesn't seem to work though....

As for the vacuum, it also has an attribute called 'status', which can have the value of 'Charging', but it could also have the value stopped / running /etc.

**Comment by benct** [comment]
Yes, having looked at some battery handling in other cards, I see that handling charging state can be complex. What I implemented in `1.1.0` should handle most basic cases, but I will have to add more customisability to handle different state values from various devices. Feel free to create a new issue for custom charging states (add some examples if you can) and I'll see if I can implement something soon-ish :)
