### ISSUE TITLE
Support string values

### ISSUE THREAD

**Issue by xstrex** [benct/lovelace-battery-entity-row#5]
Hi, I've got a few battery powered devices I monitor, where the unit is: normal or low 
When using your battery-entity-row, what unit should I be using for these devices? 

Defaulting to % is great, in most cases, for these devices, it just shows 0%, when in-fact the state is actually normal. I've tried "unit:  " & "unit: string" but not getting the result I'd expect. Are their more options for unit than "%"?

cheers

**Comment by benct** [comment]
Try `unit: false` after upgrading to `v1.1.0`. However, this card currently only supports numeric battery values, not strings like normal and low.

**Comment by xstrex** [comment]
Understood. I tried it, after upgrading, no luck. Any chance of making this a feature request?

**Comment by benct** [comment]
Make sure you clear cache/hard refresh your HA tab.. Hiding the unit works fine here.

I'll try to look into supporting string values. Let me know what the different values are. `high`, `medium`, `normal`, `low`, `empty`, etc..?

**Comment by xstrex** [comment]
I've tried clearing the cache/hard refresh, and the binary sensor shows "Unknown" when the state of the sensor is actually "Low". I've got several binary_sensors, the 2 states I've seen are "Normal" or "Low".

**Comment by benct** [comment]
Version `1.2.0` should now support string values like `normal` and `low` (and some others).
