### ISSUE TITLE
Improve Battery Charging Icons

### ISSUE THREAD

**Issue by Veldkornet** [benct/lovelace-battery-entity-row#7]
As a follow-up to #4 , some entities are a bit different and require a bit more than the boolean .

Two examples of this that I have are my iOS App devices, and my vacuum (Roomba).

Vacuum:
By default, it's using these attributes (example):
```
battery_level: 100
battery_icon: 'mdi:battery-charging-100'
status: Charging
```
The main thing here is that the status could also indicate other things than just the battery status, ie stopped, running, etc

The other is the iOS devices, using the official iOS app. These have a battery state sensor, for example: `sensor.my_iphone_battery_state` where it has the actual state being either `Charging` or `Not Charging`. This sensor also has some other attributes, such as the below:
```
Battery Level: 20
Low Power Mode: false
friendly_name: My iPhone Battery State
icon: 'mdi:battery'
device_class: battery
```

Further to that, the sensor which is actually used in the battery entity card is the `sensor.my_iphone_battery_level`. This has an attribute called `Battery State:` which seems to be referencing the battery state sensor. Attribute example:
```
Battery State: Charging
Low Power Mode: false
unit_of_measurement: '%'
friendly_name: My iPhone Battery Level
icon: 'mdi:battery-charging-20'
device_class: battery
```

Most of this can be found in the [HA Companion Documentation](https://companion.home-assistant.io/docs/core/sensors/), and more specifically, the [Battery Sensors](https://companion.home-assistant.io/docs/core/sensors/#battery-sensors)

**Comment by benct** [comment]
Version `1.2.0` added support for specifying custom charging state(s) as well as automatically supporting `on`, `charging` or `true` as valid charging states. Let me know if this does not work as expected.
